server:
  port: 10002
spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://192.168.183.128:10001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30